# Generated by Django 5.1.4 on 2026-08-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employ_Att',
        ),
        migrations.DeleteModel(
            name='Employ_Data',
        ),
    ]
