# Generated by Django 5.1.4 on 2026-08-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curd_app', '0004_delete_employ_att_delete_employ_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ_Att',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployId', models.IntegerField()),
                ('Employname', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employ_Data',
            fields=[
                ('EmployId', models.AutoField(primary_key=True, serialize=False)),
                ('Employname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Employrole', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Experince', models.CharField(max_length=20)),
                ('Salary', models.CharField(max_length=20)),
            ],
        ),
    ]
