# Generated by Django 5.1.4 on 2026-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_data',
            name='Address',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Designation',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Employname',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Employrole',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Experince',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Salary',
            field=models.CharField(max_length=2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000),
        ),
    ]
