# Generated by Django 5.1.4 on 2026-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0006_alter_employ_data_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_data',
            name='Salary',
            field=models.CharField(max_length=90000),
        ),
    ]
