# Generated by Django 5.1.4 on 2026-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0007_alter_employ_data_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_data',
            name='Address',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Experince',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Salary',
            field=models.CharField(max_length=50000),
        ),
    ]
