# Generated by Django 5.1.4 on 2026-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0008_alter_employ_data_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_data',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Designation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Employname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Employrole',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Experince',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employ_data',
            name='Salary',
            field=models.TextField(),
        ),
    ]
