# Generated by Django 5.1.4 on 2026-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0009_alter_employ_data_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_att',
            name='Employname',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='employ_att',
            name='Status',
            field=models.CharField(max_length=20000),
        ),
    ]
