# Generated by Django 5.1.4 on 2026-08-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0010_alter_employ_att_employname_alter_employ_att_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ_att',
            name='Salary',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='employ_att',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
