# Generated by Django 5.1.4 on 2026-08-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0011_employ_att_salary_alter_employ_att_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ_Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EmployId', models.IntegerField()),
                ('Employname', models.CharField(max_length=50000)),
                ('MonthlySalary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employ_att',
            name='Salary',
        ),
    ]
