# Generated by Django 5.1.4 on 2026-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0012_employ_salary_remove_employ_att_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_salary',
            name='MonthlySalary',
            field=models.TextField(),
        ),
    ]
